### ISSUE TITLE
running a mda.Universe through make_APS_input zeros ligand charges

### ISSUE THREAD

**Issue by IAlibay** [xiki-tempula/rocklinc#3]
Because of the zero-ing on line 159, the charges for the ligand in the Universe get zeroed, modifying in-place the universe being parsed

https://github.com/xiki-tempula/rocklinc/blob/14e6378e3e773626a52f552a4e76528f4d757fb3/rocklinc/rocklin_correction.py#L153-L161

I guess the simplest solution here is just to feed the charges back (i.e. akin to line 158) after line 161, or just operate on a copy of the Universe?

**Comment by xiki-tempula** [comment]
@IAlibay Thanks for opening the issue. So you would like to do something else with the universe after this, I kind of just assumed that the universe will get discarded after the calculation.

**Comment by IAlibay** [comment]
Yeah it's always useful to be able to call these things as part of a larger framework rather than a one off call. If anything, keeping hold of the Universe can be useful if you're iterating through a trajectory to see how large the variance is between frames.

**Comment by xiki-tempula** [comment]
This might be a bad practice but I fix it with the commit https://github.com/xiki-tempula/rocklinc/commit/a780446e132f8e78b5a1e01367c7948da33377a5

**Comment by IAlibay** [comment]
I _think_ it's fine, the only problem case I could think is multiprocessing, but iirc Universes are not shared objects when you do that.

If you wanted to be super secure copying the Universe would work too, but it's really overkill.
